swagger: "2.0"

info:
  title: "Hero"
  version: "1.0"

basePath: /api

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: app.post_greeting
      produces:
        - application/json;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
  /greeting/:
    get:
      summary: Get default greeting
      description: Generates a greeting message.
      operationId: app.get_greeting
      produces:
        - application/json;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"
  /heroes/:
    get:
      summary: Get all heroes
      description: Generates heroes list
      operationId: app.get_all
      produces:
        - application/json;
      responses:
        200:
          description: response
          schema:
            type: string
          examples:
            "text/json": "{\n11: Dick\n}"
  /heroes/{name}:
    post:
      summary: Add new hero
      description: Add new hero and return response
      operationId: app.post_hero
      produces:
        - application/json;
      responses:
        200:
          description: response
          schema:
            type: string
          examples:
            "text/json": "{\n11: Dick\n}"
      parameters:
        - name: name
          in: path
          description: Name of a hero 
          required: true
          type: string
  /heroes/{id}:
    get:
      summary: Update hero
      description: Update hero and return updated instance
      operationId: app.get_hero
      produces:
        - application/json;
      responses:
        200:
          description: response
          schema:
            type: string
      parameters:
        - name: id 
          in: path
          description: Id of the hero 
          required: true
          type: integer
    put:
      summary: Update hero
      description: Update hero and return updated instance
      operationId: app.put_hero
      produces:
        - application/json;
      responses:
        200:
          description: response
          schema:
            type: string
      parameters:
        - name: id 
          in: path
          description: Id of the hero 
          required: true
          type: integer
        - name: name 
          in: formData
          description: Id of the hero 
          required: true
          type: string
    delete:
      summary: Delete hero
      description: Delete hero and return updated instance
      operationId: app.delete_hero
      produces:
        - application/json;
      responses:
        200:
          description: response
          schema:
            type: string
      parameters:
        - name: id 
          in: path
          description: Id of the hero 
          required: true
          type: integer
